<template>
  <div class="app-container">
    <el-alert title="生产订单是生产执行的起点：订单按产品工艺路线拆为工序工单，每张工单维护自己的计划开始和完成时间；数量只在工单分解为执行任务时拆分。" type="info" :closable="false" show-icon class="mb8" />
    <el-form :model="queryParams" size="small" :inline="true" class="mb8">
      <el-form-item label="订单编号"><el-input v-model="queryParams.productionOrderCode" clearable placeholder="订单编号" @keyup.enter.native="load" /></el-form-item>
      <el-form-item label="订单名称"><el-input v-model="queryParams.productionOrderName" clearable placeholder="订单名称" @keyup.enter.native="load" /></el-form-item>
      <el-form-item label="客户"><el-input v-model="queryParams.clientName" clearable placeholder="客户名称" @keyup.enter.native="load" /></el-form-item>
      <el-form-item label="产品"><el-input v-model="queryParams.productName" clearable placeholder="产品名称" @keyup.enter.native="load" /></el-form-item>
      <el-form-item label="状态"><el-select v-model="queryParams.status" clearable placeholder="全部" style="width: 120px"><el-option label="待拆解" value="PREPARE" /><el-option label="部分拆解" value="SPLIT" /><el-option label="已全部拆解" value="ALL_SPLIT" /><el-option label="已完成" value="FINISHED" /></el-select></el-form-item>
      <el-form-item><el-button type="primary" icon="el-icon-search" @click="load">搜索</el-button><el-button icon="el-icon-refresh" @click="resetQuery">重置</el-button></el-form-item>
    </el-form>
    <el-row class="mb8"><el-button type="primary" icon="el-icon-plus" size="mini" @click="openAdd">新建</el-button><el-button type="success" icon="el-icon-upload2" size="mini" @click="importDialog = true">导入</el-button><el-button icon="el-icon-download" size="mini" @click="downloadTemplate">下载模板</el-button><el-button icon="el-icon-refresh" size="mini" @click="load">刷新</el-button></el-row>
    <el-table v-loading="loading" :data="rows" :header-cell-style="centerStyle" :cell-style="centerStyle">
      <el-table-column label="订单编号" prop="production_order_code" width="160" /><el-table-column label="订单名称" prop="production_order_name" min-width="200" show-overflow-tooltip /><el-table-column label="客户" prop="client_name" min-width="180" show-overflow-tooltip /><el-table-column label="产品数量" width="100"><template slot-scope="scope">{{ formatQuantity(scope.row.total_quantity) }}</template></el-table-column><el-table-column label="工单数" prop="workorder_count" width="80" /><el-table-column label="需求交期" width="160"><template slot-scope="scope">{{ parseTime(scope.row.request_date) }}</template></el-table-column><el-table-column label="状态" width="110"><template slot-scope="scope"><el-tag :type="statusType(scope.row.status)">{{ statusText(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" fixed="right" width="110"><template slot-scope="scope"><el-button v-if="canSplit(scope.row)" type="text" size="mini" @click="openSplit(scope.row)">拆生产工单</el-button><span v-else class="muted-operation">已全部拆解</span></template></el-table-column>
    </el-table>
    <pagination v-show="total>0" :total="total" :page.sync="queryParams.pageNum" :limit.sync="queryParams.pageSize" @pagination="load" />

    <el-dialog title="新建生产订单" :visible.sync="dialog" width="680px" append-to-body><el-form ref="form" :model="form" :rules="rules" label-width="105px"><el-form-item label="生产产品" prop="itemId"><el-select v-model="form.itemId" filterable placeholder="选择产品" style="width: 100%" @change="fillProduct"><el-option v-for="item in options.products" :key="item.item_id" :label="`${item.item_code} - ${item.item_name}`" :value="item.item_id" /></el-select></el-form-item><el-form-item label="客户" prop="clientId"><el-select v-model="form.clientId" filterable placeholder="选择客户" style="width: 100%"><el-option v-for="client in options.clients" :key="client.client_id" :label="`${client.client_code} - ${client.client_name}`" :value="client.client_id" /></el-select></el-form-item><el-form-item label="订单名称"><el-input v-model="form.productionOrderName" placeholder="不填时自动使用产品名称" /></el-form-item><el-row><el-col :span="12"><el-form-item label="生产数量" prop="quantity"><el-input-number v-model="form.quantity" :min="1" :step="1" :precision="0" style="width: 100%" /></el-form-item></el-col><el-col :span="12"><el-form-item label="需求交期" prop="requestDate"><el-date-picker v-model="form.requestDate" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" style="width: 100%" /></el-form-item></el-col></el-row><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" /></el-form-item></el-form><div slot="footer"><el-button @click="dialog=false">取 消</el-button><el-button type="primary" @click="submit">确 定</el-button></div></el-dialog>
    <el-dialog title="导入生产订单" :visible.sync="importDialog" width="520px" append-to-body @close="clearUpload"><el-alert title="模板会按客户编码和产品编码校验主数据；每个非空数据行创建一张生产订单，数量必须为正整数。" type="warning" :closable="false" class="mb12" /><el-upload ref="upload" drag :action="upload.url" :headers="upload.headers" :auto-upload="false" :limit="1" accept=".xls,.xlsx" :disabled="upload.isUploading" :on-progress="handleFileUploadProgress" :on-success="handleFileSuccess" :on-error="handleFileError"><i class="el-icon-upload"></i><div class="el-upload__text">将 Excel 文件拖到此处，或<em>点击选择</em></div><div slot="tip" class="el-upload__tip">仅支持 xls、xlsx 格式，首行字段不可修改。</div></el-upload><div slot="footer"><el-button @click="importDialog=false">取 消</el-button><el-button type="primary" :loading="upload.isUploading" @click="submitFile">开始导入</el-button></div></el-dialog>
    <el-dialog title="按工序拆分生产工单" :visible.sync="splitDialog" width="1220px" append-to-body @close="closeSplit"><el-alert type="info" :closable="false" class="mb12" title="每一行对应一个工艺工序工单，自动继承订单数量；请为每道工序维护计划开始和完成时间。" /><el-table v-loading="splitLoading" :data="splitRows" border size="mini" max-height="410"><el-table-column label="订单产品" min-width="190"><template slot-scope="scope"><el-select v-model="scope.row.productionOrderLineId" filterable style="width: 100%" @change="changeSplitLine(scope.row)"><el-option v-for="line in splitDetail.lines" :key="line.production_order_line_id" :label="`${line.item_code} - ${line.item_name}（数量 ${formatQuantity(line.quantity)}）`" :value="line.production_order_line_id" /></el-select></template></el-table-column><el-table-column label="工艺路线" min-width="180"><template slot-scope="scope"><el-select v-model="scope.row.routeId" placeholder="选择工艺路线" style="width: 100%" @change="changeSplitRoute(scope.row)"><el-option v-for="route in routesForRow(scope.row)" :key="route.route_id" :label="`${route.route_code} - ${route.route_name}`" :value="route.route_id" /></el-select></template></el-table-column><el-table-column label="工序" min-width="170"><template slot-scope="scope"><el-select v-model="scope.row.processId" placeholder="选择未拆工序" style="width: 100%"><el-option v-for="process in processesForRow(scope.row)" :key="process.process_id" :disabled="process.split" :label="`${process.order_num}. ${process.process_name}${process.split ? '（已拆）' : ''}`" :value="process.process_id" /></el-select></template></el-table-column><el-table-column label="工单计划开始" width="190"><template slot-scope="scope"><el-date-picker v-model="scope.row.planStartTime" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" placeholder="选择开始时间" style="width: 100%" /></template></el-table-column><el-table-column label="工单计划完成" width="190"><template slot-scope="scope"><el-date-picker v-model="scope.row.planEndTime" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" placeholder="选择完成时间" style="width: 100%" /></template></el-table-column><el-table-column label="操作" width="70" align="center"><template slot-scope="scope"><el-button type="text" icon="el-icon-delete" :disabled="splitRows.length === 1" @click="splitRows.splice(scope.$index, 1)">删除</el-button></template></el-table-column></el-table><div class="split-toolbar"><el-button type="primary" plain icon="el-icon-plus" size="mini" @click="addSplitRow">增加工序工单</el-button><el-button type="success" plain icon="el-icon-magic-stick" size="mini" @click="fillAllProcesses">一键填入全部未拆工序</el-button><span>选择同一工序两次会被系统拦截。</span></div><div slot="footer"><el-button @click="splitDialog=false">取 消</el-button><el-button type="primary" :loading="splitting" @click="submitSplit">生成生产工单</el-button></div></el-dialog>
  </div>
</template>

<script>
import { getToken } from '@/utils/auth'
import { addProductionOrder, executionOptions, getProductionOrderSplitOptions, listProductionOrders, splitProductionOrder } from '@/api/mes/pro/productionexecution'

export default {
  name: 'ProductionOrder',
  data() { return { loading: false, dialog: false, importDialog: false, splitDialog: false, splitLoading: false, splitting: false, rows: [], total: 0, queryParams: { pageNum: 1, pageSize: 10 }, options: { products: [], clients: [] }, form: {}, splitDetail: { lines: [], order: {} }, splitRows: [], upload: { isUploading: false, headers: { Authorization: `Bearer ${getToken()}` }, url: `${process.env.VUE_APP_BASE_API}/mes/pro/productionorder/importData` }, rules: { itemId: [{ required: true, message: '请选择产品', trigger: 'change' }], clientId: [{ required: true, message: '请选择客户', trigger: 'change' }], quantity: [{ required: true, message: '请输入生产数量', trigger: 'blur' }, { validator: (r, v, cb) => this.isPositiveInteger(v) ? cb() : cb(new Error('生产数量必须为正整数')), trigger: 'blur' }], requestDate: [{ required: true, message: '请选择需求交期', trigger: 'change' }] } } },
  created() { this.load(); this.loadOptions() },
  methods: {
    centerStyle() { return { textAlign: 'center' } },
    load() { this.loading = true; listProductionOrders(this.queryParams).then(r => { this.rows = r.rows || []; this.total = r.total || 0 }).finally(() => { this.loading = false }) },
    resetQuery() { this.queryParams = { pageNum: 1, pageSize: 10 }; this.load() },
    loadOptions() { executionOptions().then(r => { this.options = r.data || this.options }) },
    openAdd() { this.form = { quantity: 1, requestDate: '', clientId: null, remark: '' }; this.dialog = true; this.$nextTick(() => this.$refs.form && this.$refs.form.clearValidate()) },
    fillProduct(id) { const item = (this.options.products || []).find(r => r.item_id === id); if (item && !this.form.productionOrderName) this.$set(this.form, 'productionOrderName', `${item.item_name}生产订单`) },
    submit() { this.$refs.form.validate(ok => { if (!ok || !this.isPositiveInteger(this.form.quantity)) return; addProductionOrder(this.form).then(() => { this.$modal.msgSuccess('生产订单已创建，请按工序拆分工单'); this.dialog = false; this.load() }) }) },
    downloadTemplate() { window.open(`${window.location.origin}/download/production-order-import-template.xlsx`, '_blank') },
    clearUpload() { this.upload.isUploading = false; if (this.$refs.upload) this.$refs.upload.clearFiles() },
    handleFileUploadProgress() { this.upload.isUploading = true },
    handleFileSuccess(r) { this.upload.isUploading = false; if (r.code === 200) { this.$modal.msgSuccess(r.msg || '导入成功'); this.importDialog = false; this.load() } else this.$modal.msgError(r.msg || '导入失败') },
    handleFileError() { this.upload.isUploading = false; this.$modal.msgError('生产订单导入失败，请检查模板及网络连接') },
    submitFile() { if (!this.$refs.upload || !this.$refs.upload.uploadFiles.length) return this.$modal.msgWarning('请选择要导入的 Excel 文件'); this.$refs.upload.submit() },
    openSplit(order) { this.splitLoading = true; this.splitDialog = true; getProductionOrderSplitOptions(order.production_order_id).then(r => { this.splitDetail = r.data || { lines: [], order }; const row = this.firstSplitRow(); this.splitRows = row ? [row] : []; if (!row) this.$modal.msgWarning('该订单所有工序均已拆解') }).finally(() => { this.splitLoading = false }) },
    closeSplit() { this.splitRows = []; this.splitDetail = { lines: [], order: {} }; this.splitting = false },
    defaultPlanStart() { return this.parseTime(new Date(), '{y}-{m}-{d} {h}:{i}:{s}') },
    lineForRow(row) { return (this.splitDetail.lines || []).find(line => line.production_order_line_id === row.productionOrderLineId) },
    routesForRow(row) { const line = this.lineForRow(row); return line ? (line.routes || []) : [] },
    processesForRow(row) { const route = this.routesForRow(row).find(item => item.route_id === row.routeId); return route ? (route.processes || []) : [] },
    firstSplitRow() { for (const line of (this.splitDetail.lines || [])) for (const route of (line.routes || [])) { const process = (route.processes || []).find(item => !item.split); if (process) return { productionOrderLineId: line.production_order_line_id, routeId: route.route_id, processId: process.process_id, planStartTime: this.defaultPlanStart(), planEndTime: this.splitDetail.order.request_date || '' } } return null },
    addSplitRow() { const row = this.firstSplitRow(); if (!row) return this.$modal.msgWarning('没有未拆解工序'); this.splitRows.push(row) },
    changeSplitLine(row) { const line = this.lineForRow(row); const route = line && (line.routes || [])[0]; const process = route && (route.processes || []).find(item => !item.split); Object.assign(row, { routeId: route ? route.route_id : null, processId: process ? process.process_id : null }) },
    changeSplitRoute(row) { const process = this.processesForRow(row).find(item => !item.split); this.$set(row, 'processId', process ? process.process_id : null) },
    fillAllProcesses() { const rows = []; (this.splitDetail.lines || []).forEach(line => (line.routes || []).forEach(route => (route.processes || []).filter(process => !process.split).forEach(process => rows.push({ productionOrderLineId: line.production_order_line_id, routeId: route.route_id, processId: process.process_id, planStartTime: this.defaultPlanStart(), planEndTime: this.splitDetail.order.request_date || '' })))); this.splitRows = rows; if (!rows.length) this.$modal.msgWarning('没有未拆解工序') },
    submitSplit() { const seen = {}; for (let i = 0; i < this.splitRows.length; i += 1) { const row = this.splitRows[i]; if (!row.productionOrderLineId || !row.routeId || !row.processId || !row.planStartTime || !row.planEndTime) return this.$modal.msgWarning(`请完整填写第 ${i + 1} 行`); if (new Date(row.planEndTime).getTime() <= new Date(row.planStartTime).getTime()) return this.$modal.msgWarning(`第 ${i + 1} 行计划完成时间必须晚于开始时间`); const key = `${row.productionOrderLineId}-${row.routeId}-${row.processId}`; if (seen[key]) return this.$modal.msgWarning('同一个产品工序只能拆出一张工单'); seen[key] = true } this.splitting = true; splitProductionOrder(this.splitDetail.order.production_order_id, { splits: this.splitRows }).then(r => { this.$modal.msgSuccess(`已按工序生成 ${(r.data || []).length} 张生产工单`); this.splitDialog = false; this.load(); window.dispatchEvent(new Event('mes:workorder-refresh')) }).finally(() => { this.splitting = false }) },
    isPositiveInteger(v) { const n = Number(v); return Number.isInteger(n) && n > 0 },
    formatQuantity(v) { const n = Number(v); return Number.isFinite(n) ? String(Math.round(n)) : v },
    canSplit(row) { return !['FINISHED', 'CANCELLED', 'ALL_SPLIT'].includes(row.status) },
    statusText(s) { return ({ PREPARE: '待拆解', SPLIT: '部分拆解', ALL_SPLIT: '已全部拆解', FINISHED: '已完成', CANCELLED: '已取消' })[s] || s },
    statusType(s) { return ({ PREPARE: 'info', SPLIT: 'warning', ALL_SPLIT: 'success', FINISHED: 'success', CANCELLED: 'danger' })[s] || '' }
  }
}
</script>

<style scoped>.mb12 { margin-bottom: 12px; }.split-toolbar { margin-top: 12px; display: flex; align-items: center; gap: 12px; color: #606266; font-size: 13px; }.muted-operation { color: #909399; }</style>
