<template>
  <div class="app-container">
    <el-alert title="执行任务由工单按数量分解而来；在此查看任务、关联订单/工单/计划及实际执行记录。派工操作仍在“任务派工”菜单完成。" type="info" :closable="false" show-icon class="mb8" />
    <el-form :model="queryParams" size="small" :inline="true" class="mb8"><el-form-item label="任务编号"><el-input v-model="queryParams.taskCode" clearable placeholder="任务编号" @keyup.enter.native="load" /></el-form-item><el-form-item label="生产订单"><el-input v-model="queryParams.productionOrderCode" clearable placeholder="订单编号" @keyup.enter.native="load" /></el-form-item><el-form-item label="工单"><el-input v-model="queryParams.workorderCode" clearable placeholder="工单编号" @keyup.enter.native="load" /></el-form-item><el-form-item label="产品"><el-input v-model="queryParams.productName" clearable placeholder="产品名称" @keyup.enter.native="load" /></el-form-item><el-form-item label="工序"><el-input v-model="queryParams.processName" clearable placeholder="工序名称" @keyup.enter.native="load" /></el-form-item><el-form-item label="状态"><el-select v-model="queryParams.status" clearable placeholder="全部" style="width:120px"><el-option label="待派工" value="PREPARE" /><el-option label="待开工" value="RELEASED" /><el-option label="执行中" value="IN_PROGRESS" /><el-option label="已完成" value="FINISHED" /></el-select></el-form-item><el-form-item><el-button type="primary" icon="el-icon-search" @click="load">搜索</el-button><el-button icon="el-icon-refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-row class="mb8"><el-button icon="el-icon-refresh" size="mini" @click="load">刷新</el-button></el-row>
    <el-table v-loading="loading" :data="rows" :header-cell-style="centerStyle" :cell-style="centerStyle"><el-table-column label="任务编号" prop="task_code" width="155" /><el-table-column label="生产订单" prop="production_order_code" width="150" /><el-table-column label="生产工单" prop="workorder_code" width="150" /><el-table-column label="生产计划" prop="plan_code" width="150" /><el-table-column label="产品" prop="item_name" min-width="150" show-overflow-tooltip /><el-table-column label="工序" prop="process_name" width="120" /><el-table-column label="任务数量" prop="quantity" width="100"><template slot-scope="scope">{{ formatQuantity(scope.row.quantity) }}</template></el-table-column><el-table-column label="执行人/班组" min-width="150"><template slot-scope="scope">{{ scope.row.executor_nick || scope.row.assigned_user_nick || scope.row.team_name || '未派工' }}</template></el-table-column><el-table-column label="计划完成" prop="end_time" width="160"><template slot-scope="scope">{{ parseTime(scope.row.end_time) }}</template></el-table-column><el-table-column label="状态" width="105"><template slot-scope="scope"><el-tag :type="statusType(scope.row.status)">{{ statusText(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" fixed="right" width="90"><template slot-scope="scope"><el-button type="text" size="mini" @click="openDetail(scope.row)">查看详情</el-button></template></el-table-column></el-table>
    <pagination v-show="total>0" :total="total" :page.sync="queryParams.pageNum" :limit.sync="queryParams.pageSize" @pagination="load" />
    <el-dialog :title="`执行任务详情：${detail.task ? detail.task.task_code : ''}`" :visible.sync="dialog" width="920px" append-to-body><el-descriptions v-if="detail.task" :column="3" border size="small"><el-descriptions-item label="生产订单">{{ detail.task.production_order_code || '-' }}</el-descriptions-item><el-descriptions-item label="生产工单">{{ detail.task.workorder_code }}</el-descriptions-item><el-descriptions-item label="生产计划">{{ detail.task.plan_code || '-' }}</el-descriptions-item><el-descriptions-item label="产品">{{ detail.task.item_code }} - {{ detail.task.item_name }}</el-descriptions-item><el-descriptions-item label="工序">{{ detail.task.process_name }}</el-descriptions-item><el-descriptions-item label="任务数量">{{ formatQuantity(detail.task.quantity) }}</el-descriptions-item><el-descriptions-item label="派工对象">{{ detail.task.assigned_user_nick || detail.task.team_name || '未派工' }}</el-descriptions-item><el-descriptions-item label="实际执行人">{{ detail.task.executor_nick || '-' }}</el-descriptions-item><el-descriptions-item label="任务状态">{{ statusText(detail.task.status) }}</el-descriptions-item><el-descriptions-item label="计划时间" :span="3">{{ parseTime(detail.task.start_time) }} 至 {{ parseTime(detail.task.end_time) }}</el-descriptions-item><el-descriptions-item label="实际时间" :span="3">{{ detail.task.actual_start_time ? `${parseTime(detail.task.actual_start_time)} 至 ${parseTime(detail.task.actual_end_time)}` : '-' }}</el-descriptions-item></el-descriptions><h4>执行记录</h4><el-table :data="detail.executions || []" border size="mini" :header-cell-style="centerStyle" :cell-style="centerStyle"><el-table-column label="操作" prop="operation_type" width="100"><template slot-scope="scope">{{ scope.row.operation_type === 'START' ? '开工' : scope.row.operation_type === 'FINISH' ? '完工' : scope.row.operation_type }}</template></el-table-column><el-table-column label="操作人" prop="operator_nick" min-width="120" /><el-table-column label="操作时间" prop="operation_time" min-width="160"><template slot-scope="scope">{{ parseTime(scope.row.operation_time) }}</template></el-table-column><el-table-column label="备注" prop="remark" min-width="220" /></el-table><div slot="footer"><el-button @click="dialog=false">关 闭</el-button></div></el-dialog>
  </div>
</template>
<script>
import { getExecutionTask, listExecutionTasks } from '@/api/mes/pro/productionexecution'
export default { name: 'ExecutionTask', data() { return { loading: false, rows: [], total: 0, queryParams: { pageNum: 1, pageSize: 10 }, dialog: false, detail: {} } }, created() { this.load() }, methods: { centerStyle() { return { textAlign: 'center' } }, load() { this.loading = true; listExecutionTasks(this.queryParams).then(r => { this.rows = r.rows || []; this.total = r.total || 0 }).finally(() => { this.loading = false }) }, resetQuery() { this.queryParams = { pageNum: 1, pageSize: 10 }; this.load() }, openDetail(row) { getExecutionTask(row.task_id).then(r => { this.detail = r.data || {}; this.dialog = true }) }, formatQuantity(v) { const n = Number(v); return Number.isFinite(n) ? String(Math.round(n)) : v }, statusText(s) { return ({ PREPARE: '待派工', WAITING: '等待前序', RELEASED: '待开工', IN_PROGRESS: '执行中', FINISHED: '已完成', REVOKED: '已撤回' })[s] || s }, statusType(s) { return ({ PREPARE: 'info', WAITING: 'info', RELEASED: 'warning', IN_PROGRESS: 'primary', FINISHED: 'success', REVOKED: 'danger' })[s] || '' } } }
</script>
